### PR TITLE
Correction of the substract function #2

### PR DESCRIPTION
**Pull request by EmmaPostolec**
Hi Anna-Marie, 
I updated the function subtract in your code. :)
Hope it's fine.

### CODE REVIEW

**Review by Anna-MarieSeelen — APPROVED** [review]
Thanks!

**Comment by Anna-MarieSeelen** [comment]
It worked emma!!

**Comment by Anna-MarieSeelen** [comment]
@EmmaPostolec

**Comment by EmmaPostolec** [comment]
Nice :)

**Pull request merged**
